CREATE TABLE Student (
	STU_NUM INT (6) PRIMARY KEY,
	STU_SNAME VARCHAR (15) ,
	STU_FNAME VARCHAR (15) ,
	STU_INITIAL CHAR (1) ,
	STU_STARTDATE DATE ,
	COURSE_CODE CHAR(3),
	PROJ_NUM INT(2),
    PRIMARY KEY (STU_NUM) 
);