//1
    CREATE TABLE Student (
	STU_NUM CHAR (6) ,
	STU_SNAME VARCHAR (15) DEFAULT NULL,
	STU_FNAME VARCHAR (15) NOT NULL,
	STU_INITIAL CHAR (1) NOT NULL,
	STU_STARTDATE DATE DEFAULT NULL,
	COURSE_CODE CHAR(3) NOT NULL,
	PROJ_NUM INT (2) NOT NULL,
	PRIMARY KEY (STU_NUM)
    );

//2
 INSERT INTO Student (STU_NUM,STU_SNAME,STU_FNAME,STU_INITIAL,STU_STARTDATE,COURSE_CODE,PROJ_NUM) VALUES (01,'Snow','John','E','05-Apr-14','201',6);
 INSERT INTO Student (STU_NUM,STU_SNAME,STU_FNAME,STU_INITIAL,STU_STARTDATE,COURSE_CODE,PROJ_NUM) VALUES (02,'Stark','Arya','C','12-Jul-17','305',11);
 INSERT INTO Student (STU_NUM,STU_SNAME,STU_FNAME,STU_INITIAL,STU_STARTDATE,COURSE_CODE,PROJ_NUM) VALUES (03,'Lannister','Jamie','C','05-Sep-12','101',2);
 INSERT INTO Student (STU_NUM,STU_SNAME,STU_FNAME,STU_INITIAL,STU_STARTDATE,COURSE_CODE,PROJ_NUM) VALUES (04,'Lannister','Cercei','J','05-Sep-12','101',2);
 INSERT INTO Student (STU_NUM,STU_SNAME,STU_FNAME,STU_INITIAL,STU_STARTDATE,COURSE_CODE,PROJ_NUM) VALUES (05,'Greyjoy','Theon','I','9-Dec-15','402',14); 
 INSERT INTO Student (STU_NUM,STU_SNAME,STU_FNAME,STU_INITIAL,STU_STARTDATE,COURSE_CODE,PROJ_NUM) VALUES (06,'Tyrell','Margaery','Y','12-Jul-17','305',10);  
 INSERT INTO Student (STU_NUM,STU_SNAME,STU_FNAME,STU_INITIAL,STU_STARTDATE,COURSE_CODE,PROJ_NUM) VALUES (07,'Baratheon','Tommen','R','13-Jun-19','201',5); 

//3
 SELECT * FROM Student WHERE COURSE_CODE = 305;

//4
UPDATE Student  SET COURSE_CODE =304 WHERE STU_NUM =07;

//5
 UPDATE Student  SET COURSE_CODE =111  WHERE STU_NUM IN (03,04,05);


